// Local paths for runtime assets served from /public (no external requests).
export const DRACO_DECODER_PATH = "/draco/";
export const MEDIAPIPE_WASM_PATH = "/mediapipe/wasm";
export const FACE_LANDMARKER_MODEL_PATH = "/mediapipe/face_landmarker.task";
export const HAND_LANDMARKER_MODEL_PATH = "/mediapipe/hand_landmarker.task";
/** Byte sizes of the try-on downloads (generated by scripts/copy-wasm.mjs), for progress reporting. */
export const MEDIAPIPE_MANIFEST_PATH = "/mediapipe/manifest.json";
export const HEAD_OCCLUDER_MODEL_PATH = "/models/head-occluder.glb";
export const SHOWROOM_MODEL_PATH = "/models/showroom.glb";
/**
 * Optional demo mode (try-on without a webcam): a short looping face clip run through the same pipeline.
 * No clip is bundled. List one here (and add the files to public/demo/, see docs/demo-video.md) to offer
 * "Use demo video" on camera errors; with an empty list the option is not shown.
 */
export const DEMO_VIDEO_SOURCES: readonly { src: string; type: string }[] = [];
